### ISSUE TITLE
nextstagepropertiesjson Parameter could not be deserialized

### ISSUE THREAD

**Issue by disbenovi** [helderpinto/AzureUpdateManagerTools#3] opened 2024-04-17 19:32 UTC
Hello

Followed all the instructions, the automation account Managed Identity has the correct permissions on the Sub level.
When passing the nextstagepropertoesjson parameter on the runbook, an exception is thrown out:

_The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 7:10:52 PM - Error: Code=InvalidRequestContent; Message=The request content was invalid and could not be deserialized: 'Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'properties.template.resources.CliXml', line 7, position 6847.'._

![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/113277879/fe4218cb-e44a-4ce8-84a0-6f9e160a9343)

The output seems to show that the parameters do get converted and read as the output shows the stagename :
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/113277879/329adde5-ee41-4a00-a10e-29d00587b5a9)

However it just abruptly stops, and throws the exception.

The runtime environment is 5.1 for the Az modules, and the Powershell runbook.

**Comment by helderpinto** [comment] 2024-04-17 21:57
Hi, @disbenovi! Can you please share the values that were passed to the Input Parameters? See example below 

![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/10661605/5dd1692e-ff59-4ec9-9525-fea00b9ffe9a)

**Comment by disbenovi** [comment] 2024-04-17 22:07
Here it is!
![image](https://github.com/helderpinto/AzureUpdateManagerTools/assets/113277879/869b2ea1-1789-46a5-bb40-7327cf391248)

In text - 

[
  {
    "stageName": "TEST_Wed_2200",
    "offsetDays": 1,
    "scope": ["/subscriptions/*****"],
    "filter": {
      "resourceTypes": [
        "microsoft.compute/virtualmachines",
        "microsoft.hybridcompute/machines"
      ],
      "resourceGroups": [],
      "tagSettings": {
        "tags": {
          "os-name": ["windows2022"],
          "aum-stage": ["TEST"]
        },
        "filterOperator": "All"
      },
      "locations": [],
      "osTypes": ["Windows"]
    }
  },
  {
    "stageName": "PROD_Thur_2200",
    "offsetDays": 2,
    "scope": ["/subscriptions/******"],
    "filter": {
      "resourceTypes": [
        "microsoft.compute/virtualmachines",
        "microsoft.hybridcompute/machines"
      ],
      "resourceGroups": [],
      "tagSettings": {
        "tags": {
          "os-name": ["windows2022"],
          "aum-stage": ["PRD"]
        },
        "filterOperator": "All"
      },
      "locations": [],
      "osTypes": ["Windows"]
    }
  }
]


@helderpinto

**Comment by helderpinto** [comment] 2024-04-18 12:55
I am not seeing anything obviously wrong or prone to failure. Allow me some time to try to reproduce your issue. I'll return to you with the results soon.

**Comment by disbenovi** [comment] 2024-04-18 16:31
Appreciate it :)

**Comment by helderpinto** [comment] 2024-04-19 14:43
I was able to reproduce this issue. There was a change in a recent version of the `Az.Resources` module, in the way it processes ARM template object (as hashtables), that broke the runbook code. I pushed a new version of the runbook that uses a different approach for the ARM template deployment. Please, update your runbook code and give it a new try.

Don't forget to increase the stages offsets, because they refer to the date of the latest run of the maintenance configuration and if you keep 1-2 days offsets, the resulting date will be in the past and the deployment will fail.

If the runbook still fails for the same reason, please reopen the issue.

**Closed as completed** 2024-04-19 14:44 UTC

**Comment by disbenovi** [comment] 2024-04-19 15:35
Works now, thanks a lot for the prompt responses @helderpinto!
